#!/usr/bin/env sh
# Xsession initialization script

# Exit on error
set -e

# xresources paths
#
SYSRESOURCES='/etc/X11/Xresources'
USERRESOURCES="${HOME:+${HOME}/.Xresources}"

# xsession paths
#
SYSSESSIONDIR='/etc/X11/xinit/xinitrc.d'
USERSESSIONDIR="${HOME:+${HOME}/.xinitrc.d}"

# xmodmap keymap paths
SYSMODMAP='/etc/X11/xinit/.Xmodmap'
USERMODMAP="${HOME}/.Xmodmap"

# Merge in system resources
#
if test -f "${SYSRESOURCES}" && test -r "${SYSRESOURCES}"; then
  xrdb -merge "${SYSRESOURCES}"
elif test -d "${SYSRESOURCES}" && test -r "${SYSRESOURCES}"; then
  for __source__ in "${SYSRESOURCES}"/*; do
    if test -f "${__source__}" && test -r "${__source__}"; then
      xrdb -merge "${__source__}"
    fi
  done
fi

# Merge in user resources
#
if test -f "${USERRESOURCES}" && test -r "${USERRESOURCES}"; then
  xrdb -merge -I"${HOME}" "${USERRESOURCES}"
elif test -d "${USERRESOURCES}" && test -r "${USERRESOURCES}"; then
  for __source__ in "${USERRESOURCES}"/*; do
    if test -f "${__source__}" && test -r "${__source__}"; then
      xrdb -merge -I"${HOME}" "${__source__}"
    fi
  done
fi

# Run system config scripts
#
if test -d "${SYSSESSIONDIR}" && test -r "${SYSSESSIONDIR}"; then
  for __source__ in "${SYSSESSIONDIR}"/*; do
    if test -f "${__source__}" && test -r "${__source__}"; then
      . "${__source__}"
    fi
  done
fi

# Run user config scripts
#
if test -d "${USERSESSIONDIR}" && test -r "${USERSESSIONDIR}"; then
  for __source__ in "${USERSESSIONDIR}"/*; do
    if test -f "${__source__}" && test -r "${__source__}"; then
      . "${__source__}"
    fi
  done
fi

# Load system keymaps
#
if test -f "${SYSMODMAP}"; then
  xmodmap "${SYSMODMAP}"
fi

# Load user keymaps
#
if test -f "${USERMODMAP}"; then
  xmodmap "${USERMODMAP}"
fi

unset __source__

# vi:ft=sh
