[palette."catppuccin_mocha"]
background = "#1e1e2e"
black = "#585b70"
blue = "#74a8fc"
bright_fg = "#cdd6f4"
cursor_bg = "#f5e0dc"
cursor_fg = "#1e1e2e"
cyan = "#6bd7ca"
foreground = "#cdd6f4"
green = "#89d88b"
highlight_bg = "#585b70"
highlight_fg = "#cdd6f4"
light_black = "#585b70"
light_blue = "#74a8fc"
light_cyan = "#6bd7ca"
light_green = "#89d88b"
light_magenta = "#f2aede"
light_red = "#f37799"
light_white = "#bac2de"
light_yellow = "#ebd391"
magenta = "#f2aede"
purple = "#f5c2e7"
red = "#f37799"
selection_bg = "#585b70"
selection_fg = "#cdd6f4"
white = "#bac2de"
yellow = "#ebd391"
