[palette."catppuccin_latte"]
background = "#eff1f5"
black = "#6c6f85"
blue = "#456eff"
bright_fg = "#4c4f69"
cursor_bg = "#dc8a78"
cursor_fg = "#eff1f5"
cyan = "#2d9fa8"
foreground = "#4c4f69"
green = "#49af3d"
highlight_bg = "#acb0be"
highlight_fg = "#4c4f69"
light_black = "#6c6f85"
light_blue = "#456eff"
light_cyan = "#2d9fa8"
light_green = "#49af3d"
light_magenta = "#fe85d8"
light_red = "#de293e"
light_white = "#bcc0cc"
light_yellow = "#eea02d"
magenta = "#fe85d8"
purple = "#ea76cb"
red = "#de293e"
selection_bg = "#acb0be"
selection_fg = "#4c4f69"
white = "#bcc0cc"
yellow = "#eea02d"
