[palette."cyberdream"]
background = "#16181a"
background_alt = "#1e2124"
black = "#3c4048"
blue = "#5ea1ff"
cursor_bg = "#ffffff"
cursor_fg = "#16181a"
cyan = "#5ef1ff"
dim_black = "#1c1f22"
dim_blue = "#4f85d1"
dim_cyan = "#4fc5d1"
dim_fg = "#d0d0d1"
dim_green = "#4fd05b"
dim_magenta = "#d050c6"
dim_red = "#d05c50"
dim_white = "#d0d0d1"
dim_yellow = "#c5d050"
foreground = "#ffffff"
green = "#5eff6c"
grey = "#7b8496"
highlight_bg = "#3c4048"
highlight_fg = "#ffffff"
light_black = "#4a4d4f"
light_blue = "#7eb3ff"
light_cyan = "#7ef3ff"
light_fg = "#ffffff"
light_green = "#7eff89"
light_magenta = "#ff7ef3"
light_red = "#ff8b7e"
light_white = "#ffffff"
light_yellow = "#f3ff7e"
magenta = "#bd5eff"
orange = "#ffbd5e"
pink = "#ff5ea0"
purple = "#bd5eff"
red = "#ff6e5e"
selection_bg = "#3c4048"
selection_fg = "#ffffff"
white = "#ffffff"
yellow = "#f1ff5e"
