[palette."cyberpunk"]
background = "#332a57"
black = "#595959"
blue = "#1bccfd"
bright_fg = "#ffffff"
cursor_bg = "#21f6bc"
cursor_fg = "#999999"
cyan = "#99d6fc"
foreground = "#e5e5e5"
green = "#21f6bc"
highlight_bg = "#c1deff"
highlight_fg = "#000000"
light_black = "#595959"
light_blue = "#1bccfd"
light_cyan = "#99d6fc"
light_green = "#21f6bc"
light_magenta = "#e6aefe"
light_red = "#ff8aa4"
light_white = "#ffffff"
light_yellow = "#fff787"
magenta = "#e6aefe"
purple = "#df95ff"
red = "#ff8aa4"
selection_bg = "#c1deff"
selection_fg = "#000000"
white = "#ffffff"
yellow = "#fff787"
