[palette."cyberdream_light"]
background = "#ffffff"
background_alt = "#eaeaea"
black = "#acacac"
blue = "#0057d1"
cursor_bg = "#16181a"
cursor_fg = "#ffffff"
cyan = "#008c99"
dim_black = "#bfc0c0"
dim_blue = "#044aac"
dim_cyan = "#04747f"
dim_fg = "#16181a"
dim_green = "#04740e"
dim_magenta = "#ab049e"
dim_red = "#ab1505"
dim_white = "#16181a"
dim_yellow = "#7e6705"
foreground = "#16181a"
green = "#008b0c"
grey = "#7b8496"
highlight_bg = "#acacac"
highlight_fg = "#16181a"
light_black = "#eeeeee"
light_blue = "#3278da"
light_cyan = "#32a3ad"
light_fg = "#444647"
light_green = "#32a23c"
light_magenta = "#da32cb"
light_red = "#da4332"
light_white = "#444647"
light_yellow = "#ad9532"
magenta = "#a018ff"
orange = "#d17c00"
pink = "#f40064"
purple = "#a018ff"
red = "#d11500"
selection_bg = "#acacac"
selection_fg = "#16181a"
white = "#16181a"
yellow = "#997b00"
