[palette."dayfox"]
background = "#f6f2ee"
black = "#534c45"
blue = "#4863b6"
bright_fg = "#3d2b5a"
cursor_bg = "#3d2b5a"
cursor_fg = "#f6f2ee"
cyan = "#488d93"
foreground = "#3d2b5a"
green = "#577f63"
highlight_bg = "#e7d2be"
highlight_fg = "#3d2b5a"
light_black = "#534c45"
light_blue = "#4863b6"
light_cyan = "#488d93"
light_green = "#577f63"
light_magenta = "#8452d5"
light_red = "#b3434e"
light_white = "#f4ece6"
light_yellow = "#b86e28"
magenta = "#8452d5"
purple = "#6e33ce"
red = "#b3434e"
selection_bg = "#e7d2be"
selection_fg = "#3d2b5a"
white = "#f4ece6"
yellow = "#b86e28"
