[palette."desert"]
background="#333333"
bg="#333333"
black="#4d4d4d"
blue="#cd853f"
cursor="#00ff00"
cyan="#ffa0a0"
fg="#ffffff"
foreground="#ffffff"
green="#98fb98"
magenta="#ffdead"
purple="#ffdead"
red="#ff2b2b"
selection="#b5d5ff"
white="#f5deb3"
yellow="#f0e68c"
