[palette."github"]
background="#0d1117"
bg="#2f81f7"
black="#24292f"
blue="#0969da"
cursor="#2f81f7"
cyan="#1b7c83"
fg="#6fc1ff"
foreground="#e6edf3"
green="#116329"
magenta="#b083f0"
purple="#8250df"
red="#cf222e"
selection="#f0f3f6"
white="#6e7781"
yellow="#4d2d00"
