[palette."lab_fox"]
background = "#2e2e2e"
black = "#535353"
blue = "#db501f"
bright_fg = "#ffffff"
cursor_bg = "#7f7f7f"
cursor_fg = "#b2b2b2"
cyan = "#7d53e7"
foreground = "#ffffff"
green = "#53eaa8"
highlight_bg = "#cb392e"
highlight_fg = "#ffffff"
light_black = "#535353"
light_blue = "#db501f"
light_cyan = "#7d53e7"
light_green = "#53eaa8"
light_magenta = "#6a36b6"
light_red = "#ff6517"
light_white = "#ffffff"
light_yellow = "#fca013"
magenta = "#6a36b6"
purple = "#6b40a8"
red = "#ff6517"
selection_bg = "#cb392e"
selection_fg = "#ffffff"
white = "#ffffff"
yellow = "#fca013"
