[palette."light_owl"]
background = "#fbfbfb"
black = "#989fb1"
blue = "#288ed7"
bright_fg = "#403f53"
cursor_bg = "#403f53"
cursor_fg = "#f6f6f6"
cyan = "#2aa298"
foreground = "#403f53"
green = "#08916a"
highlight_bg = "#e0e0e0"
highlight_fg = "#403f53"
light_black = "#989fb1"
light_blue = "#288ed7"
light_cyan = "#2aa298"
light_green = "#08916a"
light_magenta = "#d6438a"
light_red = "#de3d3b"
light_white = "#f0f0f0"
light_yellow = "#daaa01"
magenta = "#d6438a"
purple = "#d6438a"
red = "#de3d3b"
selection_bg = "#e0e0e0"
selection_fg = "#403f53"
white = "#f0f0f0"
yellow = "#daaa01"
