[palette."lovelace"]
background = "#1d1f28"
black = "#4e5165"
blue = "#556fff"
bright_fg = "#ffffff"
cursor_bg = "#c574dd"
cursor_fg = "#ffffff"
cyan = "#3fdcee"
foreground = "#fdfdfd"
green = "#18e3c8"
highlight_bg = "#c1deff"
highlight_fg = "#000000"
light_black = "#4e5165"
light_blue = "#556fff"
light_cyan = "#3fdcee"
light_green = "#18e3c8"
light_magenta = "#b043d1"
light_red = "#ff4971"
light_white = "#bebec1"
light_yellow = "#ff8037"
magenta = "#b043d1"
purple = "#c574dd"
red = "#ff4971"
selection_bg = "#c1deff"
selection_fg = "#000000"
white = "#bebec1"
yellow = "#ff8037"
