[palette."melange_dark"]
background = "#292522"
black = "#867462"
blue = "#a3a9ce"
bright_fg = "#292522"
cursor_bg = "#ece1d7"
cursor_fg = "#292522"
cyan = "#89b3b6"
foreground = "#ece1d7"
green = "#85b695"
highlight_bg = "#ece1d7"
highlight_fg = "#403a36"
light_black = "#867462"
light_blue = "#a3a9ce"
light_cyan = "#89b3b6"
light_green = "#85b695"
light_magenta = "#cf9bc2"
light_red = "#d47766"
light_white = "#ece1d7"
light_yellow = "#ebc06d"
magenta = "#cf9bc2"
purple = "#b380b0"
red = "#d47766"
selection_bg = "#ece1d7"
selection_fg = "#403a36"
white = "#ece1d7"
yellow = "#ebc06d"
