[palette."melange_light"]
background = "#f1f1f1"
black = "#a98a78"
blue = "#465aa4"
bright_fg = "#f1f1f1"
cursor_bg = "#54433a"
cursor_fg = "#f1f1f1"
cyan = "#3d6568"
foreground = "#54433a"
green = "#3a684a"
highlight_bg = "#54433a"
highlight_fg = "#d9d3ce"
light_black = "#a98a78"
light_blue = "#465aa4"
light_cyan = "#3d6568"
light_green = "#3a684a"
light_magenta = "#904180"
light_red = "#bf0021"
light_white = "#54433a"
light_yellow = "#a06d00"
magenta = "#904180"
purple = "#be79bb"
red = "#bf0021"
selection_bg = "#54433a"
selection_fg = "#d9d3ce"
white = "#54433a"
yellow = "#a06d00"
