[palette."mellow"]
background = "#161617"
black = "#424246"
blue = "#b9aeda"
bright_fg = "#eaeaea"
cursor_bg = "#cac9dd"
cursor_fg = "#161617"
cyan = "#f591b2"
foreground = "#c9c7cd"
green = "#9dc6ac"
highlight_bg = "#2a2a2d"
highlight_fg = "#c1c0d4"
light_black = "#424246"
light_blue = "#b9aeda"
light_cyan = "#f591b2"
light_green = "#9dc6ac"
light_magenta = "#ecaad6"
light_red = "#ffae9f"
light_white = "#cac9dd"
light_yellow = "#f0c5a9"
magenta = "#ecaad6"
purple = "#e29eca"
red = "#ffae9f"
selection_bg = "#2a2a2d"
selection_fg = "#c1c0d4"
white = "#cac9dd"
yellow = "#f0c5a9"
