[palette."monokai_pro_light_sun"]
background = "#f8efe7"
black = "#a59c9c"
blue = "#d4572b"
bright_fg = "#2473b6"
cursor_bg = "#72696d"
cursor_fg = "#a59ca0"
cyan = "#2473b6"
foreground = "#2c232e"
green = "#218871"
highlight_bg = "#beb5b3"
highlight_fg = "#2c232e"
light_black = "#a59c9c"
light_blue = "#d4572b"
light_cyan = "#2473b6"
light_green = "#218871"
light_magenta = "#6851a2"
light_red = "#ce4770"
light_white = "#2c232e"
light_yellow = "#b16803"
magenta = "#6851a2"
purple = "#6851a2"
red = "#ce4770"
selection_bg = "#beb5b3"
selection_fg = "#2c232e"
white = "#2c232e"
yellow = "#b16803"
