[palette."monokai_pro_spectrum"]
background = "#222222"
black = "#69676c"
blue = "#fd9353"
bright_fg = "#5ad4e6"
cursor_bg = "#bab6c0"
cursor_fg = "#faf6ff"
cyan = "#5ad4e6"
foreground = "#f7f1ff"
green = "#7bd88f"
highlight_bg = "#525053"
highlight_fg = "#f7f1ff"
light_black = "#69676c"
light_blue = "#fd9353"
light_cyan = "#5ad4e6"
light_green = "#7bd88f"
light_magenta = "#948ae3"
light_red = "#fc618d"
light_white = "#f7f1ff"
light_yellow = "#fce566"
magenta = "#948ae3"
purple = "#948ae3"
red = "#fc618d"
selection_bg = "#525053"
selection_fg = "#f7f1ff"
white = "#f7f1ff"
yellow = "#fce566"
