[palette."oxocarbon"]
background = "#f2f4f8"
foreground = "#393939"
cursor_bg = "#161616"
cursor_fg = "#ffffff"
selection_bg = "#525252"
selection_fg = "#dde1e6"
highlight_bg = "#393939"
highlight_fg = "#626262"
black = "#262626"
red = "#ff7eb6"
yellow = "#ff6f00"
green = "#0f62fe"
blue = "#42be65"
cyan = "#673ab7"
purple = "#37474f"
magenta = "#be95ff"
white = "#525252"
bright_black = "#393939"
bright_red = "#ee5396"
bright_yellow = "#ff6f00"
bright_green = "#0f62fe"
bright_blue = "#08bdba"
bright_cyan = "#673ab7"
bright_magenta = "#c693ff"
bright_white = "#f2f4f8"
