[palette."oxocarbon"]
background = "#161616"
black = "#585858"
blue = "#00c15a"
bright_fg = "#ffffff"
cursor_bg = "#ffffff"
cursor_fg = "#000000"
cyan = "#ff74b8"
foreground = "#f2f4f8"
green = "#00b4ff"
highlight_bg = "#393939"
highlight_fg = "#626262"
light_black = "#585858"
light_blue = "#00c15a"
light_cyan = "#ff74b8"
light_green = "#00b4ff"
light_magenta = "#c693ff"
light_red = "#00dfdb"
light_white = "#f2f4f8"
light_yellow = "#ff4297"
magenta = "#c693ff"
purple = "#c693ff"
red = "#00dfdb"
selection_bg = "#393939"
selection_fg = "#626262"
white = "#f2f4f8"
yellow = "#ff4297"
