[palette."sakura"]
background = "#18131e"
black = "#786d69"
blue = "#9892f1"
bright_fg = "#d445d2"
cursor_bg = "#ff65fd"
cursor_fg = "#24242e"
cyan = "#eeeeee"
foreground = "#dd7bdc"
green = "#22e529"
highlight_bg = "#c05cbf"
highlight_fg = "#24242e"
light_black = "#786d69"
light_blue = "#9892f1"
light_cyan = "#eeeeee"
light_green = "#22e529"
light_magenta = "#e90cdd"
light_red = "#f41d99"
light_white = "#cbb6ff"
light_yellow = "#f59574"
magenta = "#e90cdd"
purple = "#c71fbf"
red = "#f41d99"
selection_bg = "#c05cbf"
selection_fg = "#24242e"
white = "#cbb6ff"
yellow = "#f59574"
