[palette."seoulbones_dark"]
background = "#4b4b4b"
black = "#797172"
blue = "#a2c8e9"
bright_fg = "#6c6465"
cursor_bg = "#e2e2e2"
cursor_fg = "#4b4b4b"
cyan = "#6bcacb"
foreground = "#dddddd"
green = "#8fcd92"
highlight_bg = "#777777"
highlight_fg = "#dddddd"
light_black = "#797172"
light_blue = "#a2c8e9"
light_cyan = "#6bcacb"
light_green = "#8fcd92"
light_magenta = "#b2b3da"
light_red = "#eb99b1"
light_white = "#a8a8a8"
light_yellow = "#ffe5b3"
magenta = "#b2b3da"
purple = "#a5a6c5"
red = "#eb99b1"
selection_bg = "#777777"
selection_fg = "#dddddd"
white = "#a8a8a8"
yellow = "#ffe5b3"
