[palette."seoulbones-"]
background = "#e2e2e2"
black = "#4b4b4b"
blue = "#a2c8e9"
bright = "#a8a8a8"
bright_fg = "#bfbabb"
bright1 = "#be3c6d"
bright2 = "#8fcd92"
bright3 = "#ffe5b3"
bright4 = "#a2c8e9"
bright5 = "#b2b3da"
bright6 = "#6bcacb"
brightblue = "#a2c8e9"
brightcyan = "#6bcacb"
brightgreen = "#8fcd92"
brightpurple = "#b2b3da"
brightred = "#be3c6d"
brightwhite = "#a8a8a8"
brightyellow = "#ffe5b3"
cursor = "#555555"
cursor_bg = "#555555"
cursor_fg = "#4b4b4b"
cyan = "#6fbdbe"
foreground = "#555555"
green = "#98bd99"
highlight = "#cccccc"
highlight_bg = "#cccccc"
highlight_fg = "#dddddd"
light_blue = "#a2c8e9"
light_cyan = "#6bcacb"
light_green = "#8fcd92"
light_magenta = "#b2b3da"
light_red = "#eb99b1"
light_white = "#a8a8a8"
light_yellow = "#ffe5b3"
magenta = "#a5a6c5"
purple = "#a5a6c5"
red = "#e388a3"
selection = "#cccccc"
selection_bg = "#cccccc"
selection_fg = "#555555"
selectionbackground = "#cccccc"
white = "#dddddd"
yellow = "#ffdf9b"
