[palette."seoulbones_light"]
background = "#e2e2e2"
black = "#a5a0a1"
blue = "#006f89"
bright_fg = "#bfbabb"
cursor_bg = "#555555"
cursor_fg = "#e2e2e2"
cyan = "#006f70"
foreground = "#555555"
green = "#487249"
highlight_bg = "#cccccc"
highlight_fg = "#555555"
light_black = "#a5a0a1"
light_blue = "#006f89"
light_cyan = "#006f70"
light_green = "#487249"
light_magenta = "#7f4c7e"
light_red = "#be3c6d"
light_white = "#777777"
light_yellow = "#a76b48"
magenta = "#7f4c7e"
purple = "#896788"
red = "#be3c6d"
selection_bg = "#cccccc"
selection_fg = "#555555"
white = "#777777"
yellow = "#a76b48"
