[palette."sugarplum"]
background = "#111147"
black = "#44447a"
blue = "#fa5dfd"
bright_fg = "#d0beee"
cursor_bg = "#53b397"
cursor_fg = "#93f3d7"
cyan = "#ffffff"
foreground = "#db7ddd"
green = "#52deb5"
highlight_bg = "#5ca8dc"
highlight_fg = "#ead8ff"
light_black = "#44447a"
light_blue = "#fa5dfd"
light_cyan = "#ffffff"
light_green = "#52deb5"
light_magenta = "#c6a5fd"
light_red = "#5cb5dc"
light_white = "#b577fd"
light_yellow = "#01f5c7"
magenta = "#c6a5fd"
purple = "#d0beee"
red = "#5cb5dc"
selection_bg = "#5ca8dc"
selection_fg = "#ead8ff"
white = "#b577fd"
yellow = "#01f5c7"
