[palette."synthwave_alpha"]
background = "#241b30"
black = "#7f7094"
blue = "#aa54f9"
bright_fg = "#f2f2e3"
cursor_bg = "#f2f2e3"
cursor_fg = "#241b30"
cyan = "#00fbfd"
foreground = "#f2f2e3"
green = "#0ae4a4"
highlight_bg = "#6e29ad"
highlight_fg = "#f2f2e3"
light_black = "#7f7094"
light_blue = "#aa54f9"
light_cyan = "#00fbfd"
light_green = "#0ae4a4"
light_magenta = "#ff00f6"
light_red = "#e60a70"
light_white = "#f2f2e3"
light_yellow = "#f9f972"
magenta = "#ff00f6"
purple = "#b300ad"
red = "#e60a70"
selection_bg = "#6e29ad"
selection_fg = "#f2f2e3"
white = "#f2f2e3"
yellow = "#f9f972"
