[palette."synthwave_everything"]
background = "#2a2139"
black = "#fefefe"
blue = "#36f9f6"
bright_fg = "#f0eff1"
cursor_bg = "#72f1b8"
cursor_fg = "#1a1a1a"
cyan = "#f92aad"
foreground = "#f0eff1"
green = "#72f1b8"
highlight_bg = "#181521"
highlight_fg = "#f0eff1"
light_black = "#fefefe"
light_blue = "#36f9f6"
light_cyan = "#f92aad"
light_green = "#72f1b8"
light_magenta = "#e1acff"
light_red = "#f88414"
light_white = "#fefefe"
light_yellow = "#fff951"
magenta = "#e1acff"
purple = "#c792ea"
red = "#f88414"
selection_bg = "#181521"
selection_fg = "#f0eff1"
white = "#fefefe"
yellow = "#fff951"
