[palette."tokyonight_day"]
background = "#d0d5e3"
black = "#b4b5b9"
black_500 = "#c4c8da"
blue = "#2e7de9"
bright_black = "#e1e2e7"
bright_blue = "#188092"
bright_cyan = "#006a83"
bright_fg = "#eeeeee"
bright_green = "#387068"
bright_magenta = "#d20065"
bright_red = "#c64343"
bright_white = "#3760bf"
bright_yellow = "#b15c00"
cursor_bg = "#3760bf"
cursor_fg = "#e1e2e7"
cyan = "#007197"
foreground = "#3760bf"
green = "#587539"
green_360 = "#118c74"
highlight_bg = "#99a7df"
highlight_fg = "#3760bf"
light_black = "#a1a6c5"
light_blue = "#2e7de9"
light_cyan = "#007197"
light_green = "#587539"
light_magenta = "#9854f1"
light_red = "#f52a65"
light_white = "#3760bf"
light_yellow = "#8c6c3e"
magenta = "#9854f1"
orange = "#b15c00"
purple = "#9854f1"
red = "#f52a65"
red_400 = "#f52a65"
selection_bg = "#99a7df"
selection_fg = "#3760bf"
teal = "#118c74"
white = "#6172b0"
white_400 = "#3760bf"
white_500 = "#3760bf"
yellow = "#8c6c3e"
yellow_300 = "#8c6c3e"
yellow_360 = "#8c6c3e"
