[palette."xcode_light_hc"]
background = "#ffffff"
black = "#8a99a6"
blue = "#003f73"
bright_fg = "#000000"
cursor_bg = "#000000"
cursor_fg = "#ffffff"
cyan = "#441ea1"
foreground = "#000000"
green = "#174145"
highlight_bg = "#b4d8fd"
highlight_fg = "#000000"
light_black = "#8a99a6"
light_blue = "#003f73"
light_cyan = "#441ea1"
light_green = "#174145"
light_magenta = "#9c2191"
light_red = "#ad1805"
light_white = "#000000"
light_yellow = "#78492a"
magenta = "#9c2191"
purple = "#9c2191"
red = "#ad1805"
selection_bg = "#b4d8fd"
selection_fg = "#000000"
white = "#000000"
yellow = "#78492a"
