[palette."xcode_dark"]
background = "#292a30"
black = "#7f8c98"
blue = "#6bdfff"
bright_fg = "#dfdfe0"
cursor_bg = "#dfdfe0"
cursor_fg = "#292a30"
cyan = "#dabaff"
foreground = "#dfdfe0"
green = "#acf2e4"
highlight_bg = "#414453"
highlight_fg = "#dfdfe0"
light_black = "#7f8c98"
light_blue = "#6bdfff"
light_cyan = "#dabaff"
light_green = "#acf2e4"
light_magenta = "#ff7ab2"
light_red = "#ff8170"
light_white = "#dfdfe0"
light_yellow = "#ffa14f"
magenta = "#ff7ab2"
purple = "#ff7ab2"
red = "#ff8170"
selection_bg = "#414453"
selection_fg = "#dfdfe0"
white = "#dfdfe0"
yellow = "#ffa14f"
