#!/bin/env sh
## Configure the X keyboard extension

## Preserve current traps for restoration upon return.
preserve_traps() {
  for _; do local "$_"="$(trap -p "$_")"; done
  trap "
trap '
$(for _; do printf '%s\n' "${!_:-trap -- "$_"}"; done)
' RETURN
  " RETURN
}

## Parse a list of arguments.
argparse() {
  preserve_traps ERR RETURN
  trap 'return $(('"$#"' - $# + 1))' ERR
  set -- "$@" "$1"
  while shift; do
    :
  done
}

## Parse a single argument
parsearg() {
  :
}

# Pass '-option' flag with no argument to reset options, then reconfigure.
setxkbmap 

setxkbmap                           \
  -layout   us,us                   \
  -model    pc105,pc105             \
  -variant  ,dvp                    \
  -option                           \
  -option   grp:alt_space_toggle    \
  -option   grp_led:caps            \
  -option   lv3:rwin_switch         \
  -option   caps:escape             \
  -option   shift:both_shiftlock    \
  -option   keypad:future_wang      \
  -option   kpdl:dotoss             \
  -option   kpdl:semi               \
  -option   terminate:ctrl_alt_bksp \
  -option   numpad:microsoft
