# user-tmpfiles.d/60-mpd.conf: directories and temporary files for mpd
# see tmpfiles.d(5), 20-var.conf (literal-path rule)

# Type  Path                            Mode    UID   GID   Age   Argument

# Create directories for cache, data, logs, and runtime files
d       %h/.local/var/cache/mpd         0750    -     audio -
d       %h/.local/var/mpd               0750    -     audio -
d       %h/.local/share/mpd             0750    -     audio -
d       %h/.local/share/mpd/playlists   0750    -     audio -
d       %h/.local/var/log/mpd           0750    -     audio -
d       %t/mpd                          0750    -     audio -

# Create dedicated mono and stereo playback FIFOs
p       %t/mpd/mono.fifo                0640    -     audio -
p       %t/mpd/stereo.fifo              0640    -     audio -
