# user-tmpfiles.d/60-ncmpcpp.conf: temporary files for ncmpcpp
# see tmpfiles.d(5), 20-var.conf (literal-path rule)

# Type  Path                                Mode    UID   GID   Age   Argument

# Create cache directories
d       %h/.local/var/cache/ncmpcpp         0700    -     -     -
d       %h/.local/var/cache/ncmpcpp/lyrics  0700    -     -     -
