# user-tmpfiles.d/80-cabal.conf: directories for cabal
# see tmpfiles.d(5), 20-var.conf (literal-path rule)

# Type  Path                        Mode    UID   GID   Age   Argument

# Create cache, state and log directories
d       %h/.local/var/cache/cabal   0700    -     -     -
d       %h/.local/var/cabal         0700    -     -     -
d       %h/.local/var/log/cabal     0700    -     -     4w
