##############################
# ╭─╮ ⋆ ✶ ✧ ✦ 󰫢 󰫣     󰘩 󱕅
# │┼│      󱑽 ↵ ↪ ↝ ↜ ↩ ↳
# ╰─╯  󱝁  󱝂    󰅣  󰖔 󰼱 
# ┏━┓ 󰆽           󰋇
# ┃╋┃  󰝨    󱃋   󰂖 󰉁 󱦟 
# ┗━┛          󰈸  󰞇
# 󰷏    󰲼   󰳟     󰾞 󰦍 
##############################
#
format = """\
[╭󱑽 ](fg:foreground)$os$username$hostname(\\[$localip\\])(\\[$cmd_duration\\])( $fill )($c )($python )($nodejs )($aws)$line_break\
[│󱑽 ](fg:foreground)$directory( $fill )($git_status $git_branch(:$git_commit)$git_state$git_metrics)$line_break\
[╰󱑽 ](fg:foreground)\
$character\
"""

add_newline = true

palette = 'mellow'
[palettes."mellow"]
background = "#161617"
black = "#424246"
blue = "#b9aeda"
bright_fg = "#eaeaea"
cursor_bg = "#cac9dd"
cursor_fg = "#161617"
cyan = "#f591b2"
foreground = "#c9c7cd"
green = "#9dc6ac"
highlight_bg = "#2a2a2d"
highlight_fg = "#c1c0d4"
light_black = "#424246"
light_blue = "#b9aeda"
light_cyan = "#f591b2"
light_green = "#9dc6ac"
light_magenta = "#ecaad6"
light_red = "#ffae9f"
light_white = "#cac9dd"
light_yellow = "#f0c5a9"
magenta = "#ecaad6"
purple = "#e29eca"
red = "#ffae9f"
selection_bg = "#2a2a2d"
selection_fg = "#c1c0d4"
white = "#cac9dd"
yellow = "#f0c5a9"



[localip]
ssh_only = true
format = '[$localipv4](bold fg:foreground) '
disabled = false

[fill]
symbol = ''
style = 'fg:foreground bold dimmed'

[os]
format = '[$symbol ](bold fg:foreground)'
disabled = false
[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[username]
format = '[$user](italic fg:magenta)'
show_always = true

[hostname]
#
format = '[@](bold italic dimmed fg:foreground)[$hostname](italic fg:yellow)'
ssh_only = false
# trim_at = '.*'
disabled = false

[cmd_duration]
min_time = 5000
format = '[󰉁󱦟 ](fg:foreground bold)[$duration](italic fg:green)'

[shell]
format = '[ ](bold fg:cyan)[$indicator](fg:foreground)'
disabled = true

[python]
format = '[$symbol](bold fg:foreground)[python(:$version)](italic fg:blue)'
symbol = ' '

[nodejs]
format = '[$symbol](bold fg:foreground)[node.js(:$version)](italic fg:yellow)'
symbol = '󰎙 '

[c]
# [$symbol](bold fg:foreground)
format = '[$symbol](bold fg:foreground)[c:$version ](italic fg:red)'
symbol = ''

[aws]
# [$symbol](bold fg:foreground)
format = '[$symbol](bold fg:foreground)[($profile@)aws(:$region)]($style)'
style = 'italic fg:magenta'
symbol = '󰅣 '
# region_aliases = {
#   "us-west-1" = "uw1",
#   "us-west-2" = "uw2",
#   "us-east-1" = "ue1",
#   "us-east-2" = "ue2",
#   "us-east-3" = "ue3",
# }

[directory]
format = '[󰷏 ](bold fg:foreground)[$truncation_symbol$path$read_only](italic fg:cyan)'
home_symbol = '~'
truncation_symbol = '*/'
truncation_length = 8
fish_style_pwd_dir_length = 1
read_only = ' 󰍷 '
read_only_style = 'bold fg:red'

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold fg:foreground'
# conflicted = ''
# ahead = ''
# behind = ''
# diverged = ''
# up_to_date = ''
# untracked = ''
# stashed = ''
# modified = ''
# staged = '[++\($count\)](green)'
# renamed = ''
# deleted = ''

[git_branch]
format = '[$symbol](bold fg:foreground)[$branch]($style)'
style = 'italic fg:green'
truncation_length = 32
truncation_symbol = '/'
symbol = '󰘬 '

[git_commit]
format = '[$hash([\(](fg:foreground)[$tag](bold fg:yellow)[\)](fg:foreground)]($style) '
style = 'italic fg:cyan'
commit_hash_length = 4
tag_symbol = '󰓹 '
tag_disabled = false
only_detached = true

[git_state]
format = '([:$state([\[](fg:foreground)[$progress_current of $progress_total](italic fg:foreground)[\]](fg:foreground))]($style))'
cherry_pick = '[ PICK](bold fg:red)'
merge = '[󰘭 MERGE](bold fg:magenta)'
style = 'bold fg:purple'

[time]
format = '[$time](italic fg:yellow)'
time_format = '%_I:%M%P'
disabled = false

[character]
format = '$symbol '
success_symbol = '[](fg:foreground)'
error_symbol = '[󰆽](fg:red)'
