##############################
# ╭─╮ ⋆ ✶ ✧ ✦ 󰫢 󰫣     󰘩 󱕅
# │┼│      󱑽 ↵ ↪ ↝ ↜ ↩ ↳
# ╰─╯  󱝁  󱝂    󰅣  󰖔 󰼱 
# ┏━┓ 󰆽           󰋇
# ┃╋┃  󰝨    󱃋   󰂖 󰉁 󱦟 
# ┗━┛          󰈸  󰞇
# 󰷏    󰲼   󰳟     󰾞 󰦍 
##############################
#
format = """\
[╭󱑽 ](fg:foreground bold)\
$username\
[@](bold italic fg:foreground)\
$hostname\
(\\($localip\\))\
( $cmd_duration)\
( [$fill](fg:foreground bold dimmed) )\
($c )\
($python )\
($nodejs )\
($aws )\
$line_break\
[│󱑽 ](fg:foreground bold)\
$directory\
( [$fill](fg:foreground bold dimmed) )\
($git_branch$git_commit$git_state$git_status$git_metrics )\
$line_break\
[╰󱑽 ](fg:foreground bold)\
$character\
"""

add_newline = true

palette = 'current'

[palettes."current"]
background = "#161617"
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
foreground = "#c9c7cd"
green = "#90b99f"
magenta = "#e29eca"
purple = "#e29eca"
red = "#f5a191"
selection = "#2a2a2d"
white = "#c1c0d4"
yellow = "#e6b99d"


[fill]
symbol = ''
style = 'fg:foreground bold dimmed'

[os]
format = '[ $symbol ](fg:foreground)'
disabled = true

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[username]
# [ ](bold fg:foreground)
format = '[$user](italic fg:magenta)'
show_always = true

[hostname]
#
format = '[$hostname](italic fg:yellow)'
ssh_only = false
# trim_at = '.*'
disabled = false

[cmd_duration]
min_time = 20000
format = '[[󰉁󱦟](fg:selections) $duration](italic fg:green)'

[shell]
format = '[ ](bold fg:cyan)[$indicator](fg:foreground)'
disabled = true

[python]
format = '[[$symbol](bold fg:foreground)python(:$version)](italic fg:red)'
symbol = ' '

[nodejs]
format = '[[$symbol](bold fg:foreground)node.js(:$version)](italic fg:red)'
symbol = '󰎙 '

[c]
# [$symbol](bold fg:foreground)
format = '[[$symbol](bold fg:foreground)c:$version ](italic fg:red)'
symbol = ''

[aws]
# [$symbol](bold fg:foreground)
format = '[[$symbol](bold fg:foreground)($profile@)aws(:$region)]($style)'
style = 'italic fg:cyan'
symbol = '󰅣 '
region_aliases = {
  "us-west-1" = "uw1",
  "us-west-2" = "uw2",
  "us-east-1" = "ue1",
  "us-east-2" = "ue2",
  "us-east-3" = "ue3",
}

[directory]
# [󰷏 ](bold fg:foreground)
format = '[$read_only$truncation_symbol$path](italic fg:blue)'
home_symbol = '~'
truncation_symbol = '*'
truncation_length = 32
fish_style_pwd_dir_length = 1
read_only = '󰍷 '
read_only_style = ''

[git_branch]
format = '[[$symbol](bold fg:foreground)$branch](italic fg:purple)'
truncation_length = 32
truncation_symbol = '/'
symbol = '󰘬 '

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold italic fg:green'
# conflicted = ''
# ahead = ''
# behind = ''
# diverged = ''
# up_to_date = ''
# untracked = ''
# stashed = ''
# modified = ''
# staged = '[++\($count\)](green)'
# renamed = ''
# deleted = ''

[git_commit]
commit_hash_length = 4
tag_symbol = '󰓺 '
tag_disabled = true
only_detached = true
style = 'bold fg:green'

[git_state]
format = '([:$state( \[$progress_current of $progress_total\])]($style))'
cherry_pick = '[ PICK](bold fg:red)'
merge = '[󰘭 MERGE](bold fg:purple)'
style = 'bold fg:yellow'

[time]
format = '[$time](italic fg:yellow)'
time_format = '%_I:%M%P'
disabled = false

[character]
format = '[$symbol](fg:foreground) '
success_symbol = '[](fg:foreground)'
error_symbol = '[󰆽](fg:red)'
