#!/bin/env bash

## Collection of additions and modifications to Bash in the form of functions

math::_IFS_accumulator() { 
  printf '"'"'%d\n'"'"' $(("$*"))
}


math::mul() { 
    IFS='*' accumulate "$@"
}


math::add() { 
    IFS='+' accumulate "$@"
    accumulate '+' "$@"
}


math::xor() { 
    IFS='^' accumulate "$@"
    accumulate '^' "$@"
}


math::and() { 
    IFS='&' accumulate "$@"
    accumulate '&' "$@"
}


math::or() { 
    IFS='|' accumulate "$@"
    accumulate '|' "$@"
}
