#!/bin/env bash
## alias definitions to source in bashrc
## Patrick DeYoreo

alias sudo='sudo '

alias pacs='pacman -S'
alias pacsc='pacman -Sc'
alias pacsi='pacman -Si'
alias pacss='pacman -Ss'
alias pacsu='pacman -Su'
alias pacsyyu='pacman -Syyu'

alias pacq='pacman -Q'
alias pacqdt='pacman -Qdt'
alias pacqi='pacman -Qi'
alias pacqk='pacman -Qk'
alias pacql='pacman -Ql'
alias pacqo='pacman -Qo'
alias pacqs='pacman -Qs'

alias pacr='pacman -Run'
alias pacrs='pacman -Rsun'
alias pacrcs='pacman -Rcsun'
alias pacrcss='pacman -Rcssun'
alias pacrss='pacman -Rssun'

alias pacf='pacman -F'
alias pacfl='pacman -Fl'
alias pacfo='pacman -Fo'
alias pacfsx='pacman -Fsx'
alias pacfyy='pacman -Fyy'

alias mv='mv -ibv'
alias rm='rm -Idv'

alias mkdir='mkdir -pv'

alias pcre='pcre2grep'

alias -R '{}' '{} --color=auto' ls dir vdir grep fgrep egrep pcre2grep

alias -R '{}' '{} -h' ls dir vdir df du 

alias -- pu='pushd'
alias -- po='popd'
alias -- ds='dirs'

alias -R '{}' '{} -C' ls

alias l='ls'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

alias rename='rename -ov'

alias which='type -P'

if command -pv htop >/dev/null; then
  alias top='htop'
fi

alias py='python'
alias py2='python2'
alias py3='python3'

alias xcin='xclip -selection clipboard'
alias xcout='xclip -selection clipboard -o'
alias xctee='xclip -selection clipboard -f'

alias xc1in='xclip -selection primary'
alias xc1out='xclip -selection primary -o'
alias xc1tee='xclip -selection primary -f'

alias xc2in='xclip -selection secondary'
alias xc2out='xclip -selection secondary -o'
alias xc2tee='xclip -selection secondary -f'

alias xccutfile='xclip-cutfile'
alias xccopyfile='xclip-copyfile'
alias xcpastefile='xclip-pastefile'

alias mkvenv='mkvirtualenv'
alias cdvenv='cdvirtualenv'
alias lsvenv='lsvirtualenv'
alias rmvenv='rmvirtualenv'

alias pf='printf'
alias pfd='printf '"'"'%d'"'"
alias pfi='printf '"'"'%i'"'"
alias pfo='printf '"'"'%o'"'"
alias pfu='printf '"'"'%u'"'"
alias pfx='printf '"'"'%x'"'"
alias pfX='printf '"'"'%X'"'"
alias pff='printf '"'"'%f'"'"
alias pfe='printf '"'"'%e'"'"
alias pfE='printf '"'"'%E'"'"
alias pfg='printf '"'"'%g'"'"
alias pfG='printf '"'"'%G'"'"
alias pfc='printf '"'"'%c'"'"
alias pfs='printf '"'"'%s'"'"
alias pfb='printf '"'"'%b'"'"
alias pfq='printf '"'"'%q'"'"

alias pfdn='printf '"'"'%d\n'"'"
alias pfin='printf '"'"'%i\n'"'"
alias pfon='printf '"'"'%o\n'"'"
alias pfun='printf '"'"'%u\n'"'"
alias pfxn='printf '"'"'%x\n'"'"
alias pfXn='printf '"'"'%X\n'"'"
alias pffn='printf '"'"'%f\n'"'"
alias pfen='printf '"'"'%e\n'"'"
alias pfEn='printf '"'"'%E\n'"'"
alias pfgn='printf '"'"'%g\n'"'"
alias pfGn='printf '"'"'%G\n'"'"
alias pfcn='printf '"'"'%c\n'"'"
alias pfsn='printf '"'"'%s\n'"'"
alias pfbn='printf '"'"'%b\n'"'"
alias pfqn='printf '"'"'%q\n'"'"

alias findcwd='find . -maxdepth 1'

alias credentials='gpg -d /crypt/patrick/Documents/credentials.gpg'
alias credsdecrypt='gpg /crypt/patrick/Documents/credentials.gpg'
alias credsencrypt='gpg -c /crypt/patrick/Documents/credentials'
alias credsencsign='gpg -cs /crypt/patrick/Documents/credentials'

alias groupmeminfo=\
'column'\
' --table'\
' --table-columns Member,Non-Member'\
' --columns 2'\
' --output-separator $'"'"'\t'"'"\
' <(paste --delimiters=$'"'"'\t'"'"\
' <(grep "${USER}" /etc/group) <(grep -v "${USER}" /etc/group)'\
' | sed -E '"'"'s/^\s+/- /'"'"')'\
' | sed -E '"'"'1!s/^\<|(\s)\</\1> /g'"'"\
' | expand'

alias ydla='youtube-dl \
  --extract-audio \
  --audio-quality 0 \
  --console-title \
  --format "bestaudio/best" \
  --output "${HOME}/Music/%(title)s.%(ext)s" \
  --geo-bypass \
  --ignore-errors \
  --playlist-random \
  --min-sleep-interval 1 \
  --max-sleep-interval 7 \
  --add-metadata \
  --metadata-from-title \
'"'"'^((?P<artist>.+?)\s+-\s+((?P<album>.+)\s+-\s+)?)?(?P<title>.+?)$'"'"
