#!/usr/bin/env bash
#
#
## Bash Alias Definitions
## Patrick DeYoreo
#

## If an expanded alias ends with a blank, then the next word is also checked.

alias sudo='sudo '


## -- Default Options --

alias -R '%' '% --color=auto' ls dir vdir grep pcre2grep

alias -R '%' '% --preserve-root' chgrp chmod chown

alias -R '%' '% --random-source=/dev/random' shred shuf sort

alias mv='mv -ibv'
alias rm='rm -Idv'
alias mkdir='mkdir -pv'
alias rename='rename -ov'


## -- Command Overrides --

alias which='type -P'

type -P htop >/dev/null \
  && alias top='htop'


## -- Builtin Shortcuts --

alias pu='pushd'
alias po='popd'
alias ds='dirs'

alias l='ls'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

alias pf='printf'
alias pfd='printf '"'"'%d'"'"
alias pfi='printf '"'"'%i'"'"
alias pfo='printf '"'"'%o'"'"
alias pfu='printf '"'"'%u'"'"
alias pfx='printf '"'"'%x'"'"
alias pfX='printf '"'"'%X'"'"
alias pff='printf '"'"'%f'"'"
alias pfe='printf '"'"'%e'"'"
alias pfE='printf '"'"'%E'"'"
alias pfg='printf '"'"'%g'"'"
alias pfG='printf '"'"'%G'"'"
alias pfc='printf '"'"'%c'"'"
alias pfs='printf '"'"'%s'"'"
alias pfb='printf '"'"'%b'"'"
alias pfq='printf '"'"'%q'"'"

alias pfdn='printf '"'"'%d\n'"'"
alias pfin='printf '"'"'%i\n'"'"
alias pfon='printf '"'"'%o\n'"'"
alias pfun='printf '"'"'%u\n'"'"
alias pfxn='printf '"'"'%x\n'"'"
alias pfXn='printf '"'"'%X\n'"'"
alias pffn='printf '"'"'%f\n'"'"
alias pfen='printf '"'"'%e\n'"'"
alias pfEn='printf '"'"'%E\n'"'"
alias pfgn='printf '"'"'%g\n'"'"
alias pfGn='printf '"'"'%G\n'"'"
alias pfcn='printf '"'"'%c\n'"'"
alias pfsn='printf '"'"'%s\n'"'"
alias pfbn='printf '"'"'%b\n'"'"
alias pfqn='printf '"'"'%q\n'"'"


## -- External Shortcuts --

alias pcre='pcre2grep'

alias py='python'
alias py2='python2'
alias py3='python3'

alias xclip-i='xclip -selection clipboard -i'
alias xclip-o='xclip -selection clipboard -o'
alias xclip-f='xclip -selection clipboard -f'

alias xclip-i1='xclip -selection primary -i'
alias xclip-o1='xclip -selection primary -o'
alias xclip-f1='xclip -selection primary -f'

alias xclip-i2='xclip -selection secondary -i'
alias xclip-o2='xclip -selection secondary -o'
alias xclip-f2='xclip -selection secondary -f'

alias mkvenv='mkvirtualenv'
alias cdvenv='cdvirtualenv'
alias lsvenv='lsvirtualenv'
alias rmvenv='rmvirtualenv'

alias pacs='sudo pacman --sync'
alias pacsc='sudo pacman --sync -c'
alias pacsg='pacman --sync -g'
alias pacsi='pacman --sync -i'
alias pacss='pacman --sync -s'
alias pacsu='sudo pacman --sync -u'
alias pacsyy='sudo pacman --sync -yy'
alias pacsyyu='sudo pacman --sync -yyu'

alias pacq='pacman --query'
alias pacqdt='pacman --query -dt'
alias pacqg='pacman --query -g'
alias pacqi='pacman --query -i'
alias pacqk='pacman --query -k'
alias pacqkk='pacman --query -kk'
alias pacql='pacman --query -l'
alias pacqo='pacman --query -o'
alias pacqs='pacman --query -s'

alias pacr='sudo pacman --remove -un'
alias pacrs='sudo pacman --remove -sun'
alias pacrcs='sudo pacman --remove -csun'
alias pacrcss='sudo pacman --remove -cssun'
alias pacrss='sudo pacman --remove -ssun'

alias pacf='pacman --files'
alias pacfl='pacman --files -l'
alias pacfo='pacman --files -o'
alias pacfs='pacman --files -s'
alias pacfsx='pacman --files -sx'
alias pacfyy='pacman --files -yy'

alias gpg-decrypt='gpg --decrypt'
alias gpg-symmetric='gpg --symmetric'
alias gpg-sign='gpg --sign'
alias gpg-sign-sym='gpg --sign --symmetric'


#
## -- Docker --
#

alias docker.jupyter=\
'docker run                                                           \
  --detach                                                            \
  --tty                                                               \
  --publish 8888:8888                                                 \
  --volume ~/Documents/jupyter/datascience-notebook:/home/jovyan/work \
  jupyter/datascience-notebook'

alias docker.stopall='docker stop $(docker ps -q) 2>/dev/null'

alias docker.killall='docker kill $(docker ps -q) 2>/dev/null'

alias docker.rmdead='docker rm $(docker ps -aq) 2>/dev/null'

alias docker.rmall=\
'{ docker kill $(docker ps -q); docker rm $(docker ps -aq); } 2>/dev/null'


#
## Poor-Man's Functions
#

## find non-recursively in the current directory
alias findcwd='find . -maxdepth 1'


## Print groups in member/non-member columns each sorted by gid
alias usergroups=\
'column \
  --separator=$'"'"'\t'"'"' \
  --table \
  --output-separator=$'"'"'\t'"'"' \
  <(paste --delimiters=$'"'"'\t'"'"' \
    <(grep "${USER}" /etc/group \
      | sort \
        --field-separator=: \
        --key=3g \
      | column \
        --separator=: \
        --table \
        --table-columns=GROUP,X,GID,USERS \
        --table-hide=X
    ) \
    <(grep --invert-match "${USER}" /etc/group \
      | sort \
        --field-separator=: \
        --key=3g \
      | column \
        --separator=: \
        --table \
        --table-columns=GROUP,X,GID,USERS \
        --table-hide=X
    ) | sed -E '"'"'s/^\s+/-\t/'"'"'
  ) | expand'


## Download audio from youtube into ~/Music with available metadata
alias ydla=\
'youtube-dl \
  --extract-audio \
  --audio-quality 0 \
  --console-title \
  --format "bestaudio/best" \
  --output "${HOME}/Music/%(title)s.%(ext)s" \
  --geo-bypass \
  --ignore-errors \
  --playlist-random \
  --min-sleep-interval 1 \
  --max-sleep-interval 7 \
  --add-metadata \
  --metadata-from-title \
'"'"'^((?P<artist>.+?)\s+-\s+((?P<album>.+)\s+-\s+)?)?(?P<title>.+?)$'"'"
