#!/usr/bin/env bash

## arrlib : collection of functions to manipulate arrays


##
# arr::join - join array elements with a given character
# @1: array name
# @[2]: joining character
arr::join() {
  [[ $# -ge 1 && $# -le 2 && -v $1 ]] || return 2
  trap 'printf '"'"'%s\n'"'"' "${'"${1%%:*}[*]${1##"${1%%:*}"}"'}";'"$(
    : "$(trap -p RETURN)"
    printf '%s' "${_:-trap - RETURN})"
  )" RETURN
  IFS="${2-${IFS-$' \t\n'}}" return
}
declare -ft arr::join


##
# arr::apply - apply a command to each member of an array
# @1: the command to run
#arr::map() 
#{
#}
