#!/usr/bin/env bash

# Functions to help configure the environment

# Apply configuration for the variables given as arguments
autoenv::main()
{
    while (( $# ))
    do
        if command -v "autoenv::$1" 1>/dev/null
        then
            "autoenv::$1"
        else
            printf '%s: %s: undefined\n' "${FUNCNAME[0]}" "$1" 1>&2
        fi
        shift
    done
}


# Set default browser
autoenv::BROWSER()
{
    local _BROWSER=( "$@" google-chrome firefox ) || return

    for _BROWSER in "${_BROWSER[@]}"; do
        if command -v "${_BROWSER[0]}" 1>/dev/null; then
            # shellcheck disable=SC2178
            export _BROWSER="${_BROWSER[0]}"
            break
        fi
    done
}


# Set default text editor
autoenv::EDITOR()
{
    local _EDITOR=( "$@" vim nvim nano ) || return

    for _EDITOR in "${_EDITOR[@]}"; do
        if command -v "${_EDITOR[0]}" 1>/dev/null; then
            # shellcheck disable=SC2178
            export _EDITOR="${_EDITOR[0]}"
            break
        fi
    done
}


# Set command output colors
autoenv::LS_COLORS()
{
    local IFS _LS_COLORS && command -v dircolors 1>/dev/null || return

    case "$#" in
        0)
            if [[ -f ~/.dircolors ]]; then
                IFS="'" read -r _ LS_COLORS _ < <(dircolors -b ~/.dircolors)
                export LS_COLORS="${_LS_COLORS}"
            else
                IFS="'" read -r _ LS_COLORS _ < <(dircolors -b)
                export LS_COLORS="${_LS_COLORS}"
            fi
            ;;
        1)
            if [[ -f $1 ]]; then
                IFS="'" read -r _ LS_COLORS _ < <(dircolors -b -- "$1")
                export LS_COLORS="${_LS_COLORS}"
            fi
            ;;
        *)
            IFS=':'
            export LS_COLORS="$*"
            ;;
    esac
}


# Apply default configuration
autoenv::main 'BROWSER' 'EDITOR' 'LS_COLORS'


# vi:ft=sh
