#!/usr/bin/env bash
#
# bash aliases for interactive shells
#


# Get an absolute path to this file and add it to the environment
BASH_ALIASES_FILE="$(CDPATH='' cd -- "${BASH_SOURCE%/*}" && pwd -P && echo +)"
BASH_ALIASES_FILE="${BASH_ALIASES_FILE%??}"
BASH_ALIASES_FILE="${BASH_ALIASES_FILE%/}/${BASH_SOURCE##*/}"
export BASH_ALIASES_FILE


#
# fmtalias - define aliases from a template
#
# usage: fmtalias replace-str template name ...
#
# @replace-str: string to replace in template
# @template: alias value template 
# @name: alias name and substitution for replace-str
#
# Return: 2 if called with too few arguments, 0 otherwise.
#
fmtalias()
{
  ## If too few arguments, then print usage message and return
  if (( $# < 3 )); then
    printf 1>&2 'usage: %q replace-str template name ...\n' "${FUNCNAME[0]}"
    return 2
  fi

  ## Transform args into assignments and append replace-str
  set -- "${@/%/="$2"}" "$1"
  shift 2

  ## For each argument until replace-str, create an alias
    # shellcheck disable=SC2139
  while (( $# > 1 ))
  do
    set -- "${1%%=*}" "${1#*=}" "${@:2}"
    alias -- "$1=${2//"${!#}"/"${BASH_ALIASES[$1]:-$1}"}"
    shift 2
  done
}


#
# default options
#

alias gdb='gdb -q'
alias ls='ls -Cp'
alias mkdir='mkdir -pv'
alias mv='mv -biv'
alias rm='rm -Iv'
alias rmdir='rmdir -v'
alias vim='vim -p'

#
# perform alias expansion on 1st argument
#
fmtalias {} '{} ' nohup sudo unbuffer

#
# print colored output to terminals
#
fmtalias {} '{} --color=auto' grep egrep fgrep ls dir vdir

#
# clear
#
alias c='clear'

#
# dirstack
#
alias ds='dirs'
alias po='popd'
alias pu='pushd'

#
# jobs
#
alias j='jobs -l'
alias jx='jobs -x'

#
# printf
#
pf()
{
  local flag='[-#0+, ]'
  local width='+([[:digit:]])'
  local precision='.*([[:digit:]])'
  local conversion='[diouxXeEfFgGaAcsbq]'

  if [[ $1 == *(${flag})?(${width})?(${precision})${conversion} ]]
  then
    builtin printf "%$1\n" "${@:2}"
  else
    builtin printf "$@"
  fi
}

#
# ls
#
alias l='ls'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'

#
# tmux
#
alias t='tmux'
alias ta='tmux attach'
alias tl='tmux ls'
alias tn='tmux new'

#
# python
#
alias p='python'
alias p2='python2'
alias p3='python3'
if command -v python3 1>/dev/null
then
  alias python='python3'
fi
if command -v pip3 1>/dev/null
then
  alias pip='pip3'
fi

#
# top
#
if command -v htop 1>/dev/null
then
  alias top='htop'
fi

#
# info
#
if command -v pinfo 1>/dev/null
then
  alias info='pinfo'
fi

#
# systemd shortcuts
#
alias sctl='systemctl'
alias jctl='journalctl'

#
# xclip shortcuts
#
alias xcl='xclip -sel clipboard'
alias xcl1='xclip -sel primary'
alias xcl2='xclip -sel secondary'

alias xcl-ltrim='xclip -o -sel c | sed "s/^[[:blank:]]*//" | xclip -sel c'
alias xcl-rtrim='xclip -o -sel c | sed "s/[[:blank:]]*$//" | xclip -sel c'
alias xcl-strip=\
'xclip -o -sel c | sed "s/^[[:blank:]]*\|[[:blank:]]*$//" | xclip -sel c'

alias xcl1-ltrim='xclip -o -sel p | sed "s/^[[:blank:]]*//" | xclip -sel p'
alias xcl1-rtrim='xclip -o -sel c | sed "s/[[:blank:]]*$//" | xclip -sel c'
alias xcl1-strip=\
'xclip -o -sel p | sed "s/^[[:blank:]]*\|[[:blank:]]*$//" | xclip -sel p'

alias xcl2-ltrim='xclip -o -sel s | sed "s/^[[:blank:]]*//" | xclip -sel s'
alias xcl2-rtrim='xclip -o -sel c | sed "s/[[:blank:]]*$//" | xclip -sel c'
alias xcl2-strip=\
'xclip -o -sel s | sed "s/^[[:blank:]]*\|[[:blank:]]*$//" | xclip -sel s'

#
# poor man's functions
#

# remove a trailing newline from a file
trim-nl()
{
    local MAPFILE || return

    while (( $# ))
    do
        if mapfile <"$1"
        then
            if [[ ${MAPFILE[-1]:(-1)} == $'\n' ]]
            then
                truncate -s -1 "$1"
            fi
        fi
        shift
    done
}

# find non-recursively in the current directory
alias findhere='find . -mindepth 1 -maxdepth 1'

# use vim / nvim as a pager
alias vless='/usr/share/vim/vim80/macros/less.sh'
alias nvless='/usr/share/nvim/runtime/macros/less.sh'

# Send PulseAudio input to output
alias paloop='pacmd load-module module-loopback latency_msec=8'

# Query DNS servers for my WAN IP
alias wanip='dig @resolver1.opendns.com ANY myip.opendns.com +short'
alias wanip4='dig @resolver1.opendns.com -4 myip.opendns.com +short'
alias wanip6='dig @resolver1.opendns.com -6 myip.opendns.com +short'


#
# Holberton
#
alias bettyShowFuncDoc='sed -nE '"'"'
  /^\/\*\* *$/{
    : next
    p
    n
    /^ \*\/ *$/!b next
    N
    p
    a\\n    
  }
'"'"

alias pep8='pep8 2>/dev/null'
