#!/usr/bin/env bash
#
## bash aliases for interactive shells
###


## Get a physical, absolute path to this file and put it in the environment
BASH_ALIASES_FILE=$(CDPATH= cd -- "${BASH_SOURCE[0]%/*}"; pwd; printf +)
BASH_ALIASES_FILE=${BASH_ALIASES_FILE%??}
BASH_ALIASES_FILE=${BASH_ALIASES_FILE%/}/${BASH_SOURCE[0]##*/}


###
## aliasfmt - define aliases from a template
##
## usage: aliasfmt replace-str template [name ...]
##
## @replace-str: string to replace in @template
## @template: template for alias value
## @name: alias name and substitute for @replace-str
##
## Return: 2 if called with too few arguments, 0 otherwise.
###
fmtalias()
{
  ## If too few arguments, then print usage message and return
  if (( $# < 2 )); then
    printf 1>&2 'usage: %q replace-str template [name ...]\n' "${FUNCNAME}"
    return 2
  fi

  ## Transform args into assignments and append replace-str
  set -- "${@/%/=$2}" "$1"
  shift 2

  ## For each argument until replace-str, create an alias
  while (( $# > 1 )); do
    set -- "${1%%=*}" "${1#*=}" "${@:2}"
    BASH_ALIASES[$1]=${2//"${!#}"/"${BASH_ALIASES[$1]:-$1}"}
    shift 2
  done
}


###
## default options
###

alias ls='ls -Cp'

alias mkdir='mkdir -pv'

alias mv='mv -biv'

alias rm='rm -Iv'

alias gdb='gdb -q'


###
## expand aliases given as first argument
###
fmtalias {} '{} ' nohup sudo unbuffer

###
## produce colored output in the terminal
###
fmtalias {} '{} --color=auto' grep egrep fgrep ls dir vdir


###
## misc shortcuts
###
alias c='clear'


###
## dirstack shortcuts
###
alias ds='dirs'
alias po='popd'
alias pu='pushd'


###
## jobs shortcuts
###
alias j='jobs -l'
alias jx='jobs -x'


###
## printf shortcuts
###
alias pf='printf'
printf()
{
  local flag='[-0,+# ]'
  local width='[^0[:alpha:][:cntrl:][:punct:][:space:]]*([[:digit:]])'
  local precision='.*([[:digit:]])'
  local conversion='[diouxXeEfFgGaAcsbq]'

  if [[ $1 == *(${flag})?(${width})?(${precision})${conversion} ]]; then
    builtin printf "%$1\n" "${@:2}"
  else
    builtin printf "$@"
  fi
}


###
## ls shortcuts
###
alias l='ls'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'


###
## tmux shortcuts
###
alias t='tmux'
alias ta='tmux attach'
alias tl='tmux ls'
alias tn='tmux new'


###
## python shortcuts
###
alias p='python'
alias p2='python2'
alias p3='python3'

if command -v python3 1>/dev/null; then
  alias python='python3'
fi

if command -v pip3 1>/dev/null; then
  alias pip='pip3'
fi


###
## systemd shortcuts
###
alias sctl='systemctl'
alias sctl-u='systemctl --user'

alias jctl='journalctl'
alias jctl-u='journalctl --user'


###
## xclip shortcuts
###
alias xc0='xclip -sel clipboard'
alias xc0-i='xclip -sel clipboard -i'
alias xc0-o='xclip -sel clipboard -o'
alias xc0-f='xclip -sel clipboard -f'

alias xc1='xclip -sel primary'
alias xc1-i='xclip -sel primary -i'
alias xc1-o='xclip -sel primary -o'
alias xc1-f='xclip -sel primary -f'

alias xc2='xclip -sel secondary'
alias xc2-i='xclip -sel secondary -i'
alias xc2-o='xclip -sel secondary -o'
alias xc2-f='xclip -sel secondary -f'


###
## top substitute
###
if command -v htop 1>/dev/null; then
  alias top='htop'
fi


###
## info substitute
###
if command -v pinfo 1>/dev/null; then
  alias info='pinfo'
fi


###
## poor man's functions
###

## find non-recursively in the current directory
alias findhere='find . -mindepth 1 -maxdepth 1'

## Run vim / nvim as a pager
alias nless='/usr/share/nvim/runtime/macros/less.sh'
alias vless='/usr/share/vim/vim80/macros/less.sh'

## Send PulseAudio input to output
alias paloop='pacmd load-module module-loopback latency_msec=8'

## Query DNS servers for my WAN IP
alias wanip='dig @resolver1.opendns.com ANY myip.opendns.com +short'
alias wanip4='dig @resolver1.opendns.com -4 myip.opendns.com +short'
alias wanip6='dig @resolver1.opendns.com -6 myip.opendns.com +short'

## Download the contents of a directory over http(s)
alias wgetdir='wget -e robots=off -r -np -nd -l 1 -R index.html'
alias xc0-strip='xclip -sel clipboard -o | sed '\''s/[[:blank:]]\+$//'\'' | xclip -sel clipboard'
alias xc1-strip='xclip -sel primary -o | sed '\''s/[[:blank:]]\+$//'\'' | xclip -sel primary'
alias xc2-strip='xclip -sel secondary -o | sed '\''s/[[:blank:]]\+$//'\'' | xclip -sel secondary'
alias gush='git push'
