#!/usr/bin/env bash

##
# cdls - cd into a directory and list it's contents
# @:1:($#-1) : Options for ls
# @:(-1):1:1 : The directory name

cdls()
{
  (( $# )) || {
    printf 'usage: %q [ls_options] [--] directory\n' "${FUNCNAME[0]}" 1>&2
    return 2
  }
  printf 'cd -- %q\n' "${!#}" 1>&2
  cd -- "${!#}" && ls -Cp --color=auto "${@:1:(($# ? $# : 1) - 1)}"
}


##
# mkcd - make a directory and cd into it
# @:1:($#-1): Options for mkdir
# @:(-1)  : The directory name

mkcd()
{
  (( $# )) || {
    printf 'usage: %q [mkdir_options] [--] directory\n' "${FUNCNAME[0]}" 1>&2
    return 2
  }
  if mkdir -pv "$@"; then
    printf 'cd -- %q\n' "${!#}"
    cd -- "${!#}"
  fi
}


##
# up - cd upward
# @1 : The number of levels to cd up

up()
{
  (( $# < 2 )) || {
    printf 'usage: %q [depth]\n' "${FUNCNAME[0]}" 1>&2
    return 2
  }
  (( ${1-1} > 0 )) || {
    printf '%q: depth must be a non-negative integer\n' "${FUNCNAME[0]}" 1>&2
    return 1
  }
  trap 'cd "$(printf '"'"'%.s../'"'"' {1..'"$(( ${1-1} ))"'})"'$'\n'"$(
  : "$(trap -p RETURN)"
  printf '%s' "${_:-trap - RETURN}"
  )" RETURN
}

declare -ft up


##
# lstype - print a long listing of each command
# @ : Command names

lstype()
{
  while (( $# )); do
    ls -Cp --color=auto -l "$(type -ap "$1")"
    shift
  done
}
