#!/usr/bin/env bash
## Aliases for docker
## Patrick DeYoreo <pdeyoreo@gmail.com>


## Basic docker command aliases

alias doc='docker'
alias doc.attach='docker attach'
alias doc.build='docker build'
alias doc.commit='docker commit'
alias doc.config='docker config'
alias doc.container='docker container'
alias doc.cp='docker cp'
alias doc.create='docker create'
alias doc.diff='docker diff'
alias doc.events='docker events'
alias doc.exec='docker exec'
alias doc.export='docker export'
alias doc.help='docker help'
alias doc.history='docker history'
alias doc.image='docker image'
alias doc.images='docker images'
alias doc.import='docker import'
alias doc.info='docker info'
alias doc.inspect='docker inspect'
alias doc.kill='docker kill'
alias doc.load='docker load'
alias doc.login='docker login'
alias doc.logout='docker logout'
alias doc.logs='docker logs'
alias doc.network='docker network'
alias doc.node='docker node'
alias doc.pause='docker pause'
alias doc.plugin='docker plugin'
alias doc.port='docker port'
alias doc.ps='docker ps'
alias doc.kill='docker kill'
alias doc.pull='docker pull'
alias doc.push='docker push'
alias doc.rename='docker rename'
alias doc.restart='docker restart'
alias doc.rm='docker rm'
alias doc.rmi='docker rmi'
alias doc.run='docker run'
alias doc.save='docker save'
alias doc.search='docker search'
alias doc.secret='docker secret'
alias doc.service='docker service'
alias doc.stack='docker stack'
alias doc.start='docker start'
alias doc.stats='docker stats'
alias doc.stop='docker stop'
alias doc.swarm='docker swarm'
alias doc.system='docker system'
alias doc.tag='docker tag'
alias doc.top='docker top'
alias doc.trust='docker trust'
alias doc.unpause='docker unpause'
alias doc.update='docker update'
alias doc.version='docker version'
alias doc.volume='docker volume'
alias doc.wait='docker wait'



## Stop all running containers
alias doc.stopall='docker stop $(docker ps -q) 2>/dev/null'

## Kill all running containers
alias doc.killall='docker kill $(docker ps -q) 2>/dev/null'

## Remove all dead containers
alias doc.rmdead='docker rm $(docker ps -aq) 2>/dev/null'

## Remove all containers
alias doc.rmall='{ doc.kill $(doc.ps -q); doc.rm $(doc.ps -aq); } 2>/dev/null'



## Create a new jupyter datascience notebook container
## usage: doc.jupyter-notebook [-d] [--rm] [-p host-port] [-v host-directory]
doc.jupyter-nb() {

  ## Initialize local variables
  local usage='usage: %q [-d] [--rm] [-p host-port] [-v host-dir] [image]' &&
    local -a cmd=( docker run --tty )  || {
    printf '%q: Cannot assign local variables\n' "${FUNCNAME}" 1>&2 
    return 10
  }

  ## Parse options and construct command
  while [[ $1 == -?* ]]; do
    case $1 in
      --)
        shift
        break
        ;;
     -p|--port)
        shift
        cmd+=( -p "${1:-"${JUPYTER_PORT:-"8888"}"}:8888" )
        shift || break
        ;;
      -v|--volume)
        shift
        cmd+=( -v "${1:-"${JUPYTER_DIR:-"${PWD}"}"}:/home/jovyan/work" )
        shift || break
        ;;
      -d|--detach)
        cmd+=( -d )
        shift
        ;;
      --rm)
        cmd+=( --rm )
        shift
        ;;
      -h|--help)
        printf "${usage}\n" "${FUNCNAME[0]}"
        return 0
        ;;
      *)
        printf "${usage}\n" "${FUNCNAME[0]}" 1>&2
        return 2
        ;;
    esac
  done


  if (( $# > 1 )); then
    { printf "%q: %q: too many arguments\n" "${0##*/}" "${FUNCNAME[0]}"
      printf "${usage}\n" "${FUNCNAME[0]}"
    } 1>&2
    return 2
  fi

  if (( $# )); then
    cmd+=( "jupyter/${1#*/}" )

  else
    read -r "cmd[${#cmd[@]}]" < <(
      docker image ls --format='{{.Repository}}' 'jupyter/*-notebook'
      printf 'jupyter/scipy-notebook\n'
    )
  fi

  "${cmd[@]}"
}



## vim:et:ft=sh:sts=2:sw=2:ts=8
doc.jupyter-token() {
local -A ps=( ) tokens=( )
  while IFS=':' read -r 'ps[id]' 'ps[image]'; do
    [[ ${ps['image']} == jupyter/*-notebook &&
          $(docker logs "${ps['id']}") =~ https?://.*/\?token=([^[:space:]]*)
    ]] && tokens["${ps['id']}"]="${BASH_REMATCH[1]}" || unset -v 'ps[@]' 
  done < <(docker ps --format '{{.ID}}:{{.Image}}')
  for _ in "${!tokens[@]}"; do
    printf '%q\t%q\n' "$_" "${tokens["$_"]}"
  done
}
