#!/usr/bin/env bash
#
## history_extensions: bash command history extensions
###


###
## reload_history - load command history from the history file
###
history::reload()
{
  history -c && history -r
}


###
## sync_history - synchronize command history with the history file
###
history::sync()
{
  history -n && history -w && history::reload
}


###
## tmp_history - store history in a tmp file
###
history::tmp() 
{ 
    HISTFILE="$(mktemp --tmpdir bash_history-XXX)" &&
        trap 'rm -f "${HISTFILE}"' EXIT
}

# vi:ft=sh
