#!/usr/bin/env bash
#
## aliases, functions and variables for Holberton
###

alias gcc='gcc -Wall -Werror -Wextra -pedantic'

hbtn-project()
{
  local REPLY
  case $# in
    0)
      if [[ -n ${hbtn_project} ]]; then
        cd -- "${hbtn_project}" || unset -v hbtn_project
      else
        printf 1>&2 '%q: project directory is not set\n' "${FUNCNAME[0]}"
        printf 1>&2 'Supply a directory name to set it\n'
        return 0
      fi
      ;;
    1)
      if [[ -n ${hbtn_project} ]]; then
        read -r -p 'Change the active project directory? [Y/n] ' REPLY
        if [[ ${REPLY^} != Y* ]]; then
          printf 'Aborting.\n'
          return 0
        fi
      fi
      if __hbtn-project-set "$1"; then
          printf 'Project directory set to %q\n' "${hbtn_project}"
        return 0
      else
        printf 'Refusing to set project directory to %q\n' "$1"
        return 1
      fi
      ;;
    *)
      printf 1>&2 '%q: too many arguments\n' "${FUNCNAME[0]}"
      printf 1>&2 'usage: %q [directory]\n'  "${FUNCNAME[0]}"
      return 2
      ;;
  esac
}

__hbtn-project-set()
{
    local hbtn_project &&
        hbtn_project="$(CDPATH='' cd -- "${1:-.}" && pwd && printf +)" &&
        hbtn_project="${hbtn_project%??}" || return

    # shellcheck disable=SC2016
    sed -i -E '
    /^export hbtn_project=/{
      : old
      /(^|[^\])(\\\\)*\\$/{
        N
        b old
      }
      z
      : new
      a export hbtn_project='"${hbtn_project@Q}"'
      : cat
      N
      b cat
    }
    $b new
    ' "${BASH_SOURCE[0]}" && declare -gx hbtn_project="${hbtn_project}"
}












export hbtn_project='/home/pat/Documents/Holberton/Projects/holbertonschool-higher_level_programming'
