#!/usr/bin/env bash
## Function for manipulating the PATH variable


if  (( __libpath__ ))
then
    [[ $0 != "${BASH_SOURCE[0]}" ]] && return || exit 0
else
    (( __libpath__ = 1 ))
fi


path::append() {
  for _; do
    case ":${PATH}:" in
      *:"$_":*)
        ;;
      *)
        PATH="${PATH:+"${PATH}:"}$_"
        ;;
    esac
  done
  export PATH
}


path::prepend() {
  for _; do
    case ":${PATH}:" in
      *:"$_":*)
        ;;
      *)
        PATH="$_${PATH:+":${PATH}"}"
        ;;
    esac
  done
  export PATH
}


path::remove() {
  PATH=":${PATH-}:"
  for _; do
    PATH="${PATH//:"$_":/:}"
  done
  PATH="${PATH:1:(-1)}"
  export PATH
}
