#!/usr/bin/env bash
## Function for manipulating the PATH variable


path::append() {
  for _; do
    case ":${PATH}:" in
      *:"$_":*)
        ;;
      *)
        PATH="${PATH:+"${PATH}:"}$_"
        ;;
    esac
  done
  export PATH
}


path::prepend() {
  for _; do
    case ":${PATH}:" in
      *:"$_":*)
        ;;
      *)
        PATH="$_${PATH:+":${PATH}"}"
        ;;
    esac
  done
  export PATH
}


path::remove() {
  PATH=":${PATH-}:"
  for _; do
    PATH="${PATH//:"$_":/:}"
  done
  PATH="${PATH:1:(-1)}"
  export PATH
}
