#!/usr/bin/env bash

# Bash readline bindings


__rl_surround() {
  READLINE_LINE=$1${READLINE_LINE}$2
  READLINE_POINT=$((READLINE_POINT + ${#1}))
}


__rl_quote() {
  local old_len=${#READLINE_LINE}
  READLINE_LINE=${READLINE_LINE@Q}
  READLINE_POINT=$((READLINE_POINT + ${#READLINE_LINE} - old_len - 1))
}


#bind -x '"\eOP": __rl_F1'
bind -x '"\eOQ": __rl_quote'
bind -x '"\eOR": __rl_surround \" \"'
bind -x '"\eOS": __rl_surround \$\( \)'
bind -x '"\e[15~": __rl_surround \( \)'
bind -x '"\e[17~": __rl_surround "sudo "'
bind -x '"\e[18~": __rl_quote && __rl_surround "su -c "'
#bind -x '"\e[19~": __rl_F8'
#bind -x '"\e[20~": __rl_F9'
#bind -x '"\e[21~": __rl_F10'
#bind -x '"\e[23~": __rl_F11'
#bind -x '"\e[24~": __rl_F12'

bind -x '"\M-C": printf %s "${READLINE_LINE}" | xclip -i -sel clipboard'
